enum ScreenNames {
	Dashboard,
	About,
	ReleaseNotes,
	ForgotPassword,
	Login,
	Signup,
	PatientExercises,
	Gallery,
	PatientDiet,
	PatientProgress,
	Profile,
	PatientSchedule,
	AdminExerciseDetails,
	AdminExercises,
	AdminExercisesList,
	Patient,
	PatientData,
	PatientDataEditor,
	PatientGallery,
	Patients,
	PatientProfile,
	AddSchedule,
	Schedule,
}

export default ScreenNames;